//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kino.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Beam Angle = {0} deg..
        /// </summary>
        internal static string BeamAngle {
            get {
                return ResourceManager.GetString("BeamAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect a device first!.
        /// </summary>
        internal static string ConnectDeviceFirst {
            get {
                return ResourceManager.GetString("ConnectDeviceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grammar version=&quot;1.0&quot; xml:lang=&quot;en-US&quot; root=&quot;rootRule&quot; tag-format=&quot;semantics/1.0-literals&quot; xmlns=&quot;http://www.w3.org/2001/06/grammar&quot;&gt;
        ///  &lt;rule id=&quot;rootRule&quot;&gt;
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;
        ///        &lt;tag&gt;BRUSH&lt;/tag&gt;
        ///        &lt;one-of&gt;
        ///          &lt;item&gt; brush &lt;/item&gt;
        ///          &lt;item&gt; paint &lt;/item&gt;
        ///          &lt;item&gt; paintbrush &lt;/item&gt;
        ///        &lt;/one-of&gt;
        ///      &lt;/item&gt;
        ///      &lt;item&gt;
        ///        &lt;tag&gt;ERASER&lt;/tag&gt;
        ///        &lt;one-of&gt;
        ///          &lt;item&gt; erase &lt;/item&gt;
        ///          &lt;item&gt; eraser &lt;/item&gt;
        ///          &lt;item&gt; eras [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ready Kinect found!.
        /// </summary>
        internal static string NoKinectReady {
            get {
                return ResourceManager.GetString("NoKinectReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write screenshot to.
        /// </summary>
        internal static string ScreenshotWriteFailed {
            get {
                return ResourceManager.GetString("ScreenshotWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot saved to.
        /// </summary>
        internal static string ScreenshotWriteSuccess {
            get {
                return ResourceManager.GetString("ScreenshotWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Source Angle = {0} deg..
        /// </summary>
        internal static string SourceAngle {
            get {
                return ResourceManager.GetString("SourceAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence Level = {0}.
        /// </summary>
        internal static string SourceConfidence {
            get {
                return ResourceManager.GetString("SourceConfidence", resourceCulture);
            }
        }

        internal static string SpeechGrammar
        {
            get
            {
                return ResourceManager.GetString("SpeechGrammar", resourceCulture);
            }
        }
    }
}
